# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.3
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: iskysun96@gmail.com
author_name: iskysun96
cloud_provider: vercel
contract_name: charity_crowdfunding
deployment_language: typescript
preset_name: production
project_name: charity-crowdfunding-python

