# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: iskysun96@gmail.com
author_name: iskysun96
contract_name: charity_crowdfunding
deployment_language: typescript
preset_name: production
project_name: charity-crowdfunding-python-contracts

